# Conclusion

## What we learned

We came into this project with an idea of how certain sports may be correlated with mental health outcomes. In our analyses, however, we found that these correlations are not as strong as we had thought. For example, we had expected that the critical nature of artistic sports like dance and gymnastics would result in more negative mental health responses among participants compares to goal-oriented sports like baseball or track, but the data shows that the type of sport did not have a strong connection to the mental health responses. In fact, the most noticeable difference in any calculated score was not found while faceting by sport, but by gender; the male athletes surveyed generally admitted to more risky behavior than the female athletes.

Rather than be disappointed that we did not find strong correlations between sports and mental health, we can instead take a moment to recognize how personal experiences and biases may lead us to make predictions that do not align with the facts.


## Limitations

The initial survey contained nearly six hundred responses from each participant, so there was a lot of information; we had to make some decisions to decide which information to include and excluding in hopes of best answering our questions. As a result, we may have omitted responses that could have led to interesting insights if we had only asked questions targetting those variables.

We also made a decision to focus on only those respondents participating in a university sports at the time of the survey. Each participant was instructed to indicate all of the sports they participated in, at what level, and when; but to bring consistency to our population, we considered on the primary sport of each participant at the time the survey was completed. If we had a larger population of respondents, we could have expanded the conversation to subset the responses by college vs. community vs. high school sport, responses of athletes who played for several years as opposed to a single year, responses of athletes who play multiple sports as opposed to one, and more.


## Future directions

A next step of this data analysis would be to analyze the mental health of a different population of athletes, namely professionals. While our data discussed responses of college students from a single university in the United States, asking the same questions of professional and analyzing the results could verify or challenge the conclusions we obtained here. We anticipate this being interesting because professional athletes likely consider their sport to be a much more significant part of their lives than college athletes, and the pressures of performing for income, fame, or prestigious titles may affect depression and anxiety rates, motivating reasons, and outlooks on success.

Furthermore, expanding the study to include many participates of each type of sport across several demographics, countries, and ages could give additional insights into how different populations' results vary among the different sub-populations. With more observations in each subset of the surveyed population, we could see which factors truly influence the correlations that are present.
